export enum PackageStatus {
    RECEIVED = 'RECEIVED',
    IN_TRANSIT = 'IN-TRANSIT',
    RECEIVED_AT_LOCAL_OFFICE = 'RECEIVED AT LOCAL OFFICE',
    SCHEDULE_FOR_DELIVERY = 'SCHEDULED FOR DELIVERY',
    DELIVERED = 'DELIVERED'
}